### ISSUE TITLE
选择器委托事件

### ISSUE THREAD

**Issue by aofong** [bh-lay/toucher#2]
要是可以支持选择器委托事件就好了

**Comment by bh-lay** [comment]
事件委托是支持的，但目前只支持class，目前时间比较紧，等到项目空下来，加上tagname和ID的支持，复杂的组合及属性选择暂时不考虑了！

**Comment by DMQ** [comment]
touch事件中用eventMark缓存e会使阻止冒泡失效

**Comment by bh-lay** [comment]
不好意思，不清楚你这里提到的 `eventMark` 指的是哪一块，能描述的在详细一点么，谢谢！

**Comment by DMQ** [comment]
在```touchend```这个函数中你说到的 ```//touchend中，拿不到坐标位置信息，故使用全局保存下的事件```因为这个而弃用了```touchend```中的```event```，而是使用了```touchstart```或```touchmove```中保存的event，这样会导致```touchen````中触发的事件无法使用阻止冒泡和阻止默认行为。建议可以在```touchend```中可以使用```changedTouches```代替```touches```来取坐标位置信息

**Comment by bh-lay** [comment]
明白了，灰常感谢反馈，我会尽快修复这个问题，另外此issue是针对事件委托的，我新开了一个[issue#3](https://github.com/bh-lay/toucher/issues/3)，最新的进度我会更新在这里，谢谢！
