### ISSUE TITLE
为什么不用这种方式进行委托

### ISSUE THREAD

**Issue by MeCKodo** [bh-lay/toucher#8]
```
var box = document.getElementById("box");
	box.addEventListener('click',function(e) {
		var target = e.target;
		if(e.target.className = "item") {
			console.log('ok');
		}
        })
```

**Comment by bh-lay** [comment]
抱歉，这么晚才回ISSUE。

首先，你给的例子里的`e.target.className = "item"`是错误用法，至少应该是`==`。

其次，判断是否有`class`，并不能简单的用`classname`，因为同一个元素可能会同时有好几个`class`，或者前后可能会有空格。

再者，`target`到绑定事件元素之间有好几层元素很正常，因此必须有自`target`向绑定事件的元素查询对比的过程。

如`div > .classA > span`，事件绑定的是`div`监听的是`.classA`，但是点击的是`span`，此时的`target`并不满足你提供的例子里的条件，但是从事件上来说确实应该被触发的。

综上，事件委托实现起来其实并不可能只通过这几行代码就能搞得定，而且还不讨论某个回调里会有住址向上传递事件的情况。

**Comment by MeCKodo** [comment]
```JavaScript
body.addEventListener('click',function(e) { 
	var target = e.target;
	delegate(target,'.cliceme',function() {  
		console.log(this);
	});
},false);
function delegate(target,selector,fn) {
	var nodes = document.querySelectorAll(selector);
	for (var i = 0; i < nodes.length; i++) {
		if (nodes[i] == target) {
			fn.call(nodes[i]);
		}
	}
}
```

是否能用这种方式模拟事件代理？

**Comment by bh-lay** [comment]
要监听的元素和'target'大多数时候并不是同一个，而是有上下层级关系。

还是拿我上面的例子，思考下你提供的代码能不能完成。

> 如`div > .classA > span`，事件绑定的是`div`监听的是`.classA`，但是点击的是span。
